-- ================================================
-- ShifaBot - AI Medical Diagnosis Expert System
-- MySQL Database Schema
-- ================================================

-- Create database
CREATE DATABASE IF NOT EXISTS shifabot_db
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE shifabot_db;

-- ================================================
-- Table: users
-- Stores user authentication and profile data
-- ================================================
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user' COMMENT 'user or admin',
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Add columns to existing tables (run these if upgrading from an older version)
ALTER TABLE users ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'user' COMMENT 'user or admin';
ALTER TABLE users ADD COLUMN is_active TINYINT(1) NOT NULL DEFAULT 1;

-- ================================================
-- Seed: Default Admin Account
-- Email: hanzlasial690@gmail.com / Password: 654321
-- Uses bcrypt hash generated by Flask-Bcrypt
-- ================================================
INSERT IGNORE INTO users (name, email, password_hash, role, is_active)
VALUES (
    'Admin',
    'hanzlasial690@gmail.com',
    '$2b$12$uMh72619gyGZ5vd.DIvA1.j8iJG9n996zWPrYZ7u.CxSDT4KB2PES',
    'admin',
    1
);

-- ================================================
-- Table: consultations
-- Stores all diagnosis records (form & chatbot)
-- ================================================
CREATE TABLE IF NOT EXISTS consultations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    age INT NOT NULL,
    gender VARCHAR(20) NOT NULL,
    medical_history TEXT DEFAULT NULL,
    symptoms TEXT NOT NULL,
    duration VARCHAR(100) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    mode VARCHAR(20) NOT NULL COMMENT 'form or chatbot',
    chat_log TEXT DEFAULT NULL COMMENT 'JSON string for chatbot conversations',
    ai_analysis TEXT DEFAULT NULL COMMENT 'JSON string of possible conditions',
    medication_recs TEXT DEFAULT NULL,
    food_recs TEXT DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_consultations_user_id (user_id),
    CONSTRAINT fk_consultations_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
